[package]

name = "azure"
version = "0.1.0"
authors = ["The Servo Project Developers"]

build = "make -f makefile.cargo"

[dependencies.geom]

git = "https://github.com/servo/rust-geom"

[dependencies.skia]

git = "https://github.com/servo/skia"
branch = "upstream-2014-06-16"

[dependencies.xlib]

git = "https://github.com/servo/rust-xlib"

[dependencies.egl]

git = "https://github.com/servo/rust-egl"

[dependencies.freetype]

git = "https://github.com/servo/rust-freetype"

[dependencies.core_foundation]

git = "https://github.com/servo/rust-core-foundation"

[dependencies.core_graphics]

git = "https://github.com/servo/rust-core-graphics"

[dependencies.core_text]

git = "https://github.com/servo/rust-core-text"
